version: '3.8'

services:
  elasticsearch2:
    container_name: elasticsearch2
    build:
      context: elasticsearch
      args:
        ELK_VERSION: 7.10.1
    volumes:
      - type: volume
        source: elasticsearch2
        target: /usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  postgres2:
    # Use the official image from PostgreSQL & PostGIS
    container_name: postgres2
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"
    volumes:
      - postgres2:/var/lib/postgresql/data
      - ./shared_volume:/shared_volume

volumes:
  elasticsearch2:
  postgres2:
