ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

# RUN cd /usr/share/logstash/lib && yum https://jdbc.postgresql.org/download/postgresql-42.2.5.jar